name: Pull Request

on: 
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  label:
    needs: [size]
    name: Set Labels
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3.0.0

      - name: "Package labels"
        uses: donmahallem/lerna-label@v0.1.15
        with:
          github_secret: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Conventional labels"
        uses: bcoe/conventional-release-labels@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          
  build:
    needs: [size, label]
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build